name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write  # To publish GitHub release and commit changes
  issues: write    # To comment on released issues
  pull-requests: write  # To comment on released PRs
  id-token: write  # For npm provenance signing

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for semantic-release
          persist-credentials: false  # For @semantic-release/git on protected branches

      - name: Sync with Remote
        run: |
          git fetch origin
          git reset --hard origin/main
        continue-on-error: true  # Continue even if sync fails (e.g., no changes)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use latest LTS
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
