name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write  # To publish GitHub release and commit changes
  issues: write    # To comment on released issues
  pull-requests: write  # To comment on released PRs
  id-token: write  # For npm provenance signing

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better provenance statement
          persist-credentials: false  # For @semantic-release/git on protected branches

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use latest LTS (adjust if needed)
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release